### ISSUE TITLE
E_ERROR was caused in line 244 of the file /admin-init_rvy.php

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Revisions#593]
> Revisions stopped working with the last update. It no longer schedules, but immediately posts. Last time we had this issue it was stated that the free version wasn't supported. Site admin just purchased and I installed the Pro version and having the same issue. The attached error just came across.

```
An  error of type E_ERROR was caused in line 244 of the file  /homepages/20/d606381800/htdocs/wp-content/plugins/revisionary-pro/admin/admin-init_rvy.php.  

Error message: Uncaught Error: Call to undefined function  get_current_screen() in  /homepages/20/d606381800/htdocs/wp-content/plugins/revisionary-pro/admin/admin-init_rvy.php:244 Stack trace: #0 /homepages/20/d606381800/htdocs/wp-includes/class-wp-hook.php(303): rvy_admin_init('') 
#1  /homepages/20/d606381800/htdocs/wp-includes/class-wp-hook.php(327):  WP_Hook->apply_filters(NULL, Array) 
#2 /homepages/20/d606381800/htdocs/wp-includes/plugin.php(470): WP_Hook->do_action(Array) 
#3 /homepages/20/d606381800/htdocs/TorahFamily.org-2.0/wp-settings.php(600): do_action('wp_loaded') 
#4 /homepages/20/d606381800/htdocs/wp-config.php(82): require_once('/homepages/20/d...') 
#5 /homepages/20/d606381800/htdocs/wp-load.php(50): require_once('/homepages/20/d...') 
#6 /homepages/20/d606381800/htdocs/wp-admin/admin.php(34): require_once('/homepages/20/d...') #7 {main} thrown
--
```

**Comment by agapetry** [comment]
@stevejburge I have a fix for that line 244 error, but it is unrelated to the reported scheduling issue.
